// GENERATED FROM JSON SHEETS. Edit Sheets/*.json first.
namespace UltraHaul.Design {
public readonly struct Assets_V1 { public const string Id = "v1"; public const string Bundle = "models"; public const string Key = "438442920efb1e24fa03e81636cfc9d4"; public const string MeshName = "v1_mdl"; public const string TextureKey = "none"; public const float Height = 1.8f; public const float RotateX = -90.0f; public const float RotateY = 180.0f; public const float RotateZ = 0.0f; public const string IdleClip = "Idle"; public const string FireClip = "none"; public const string WalkClip = "Running"; public const string ArmColor = "0.02,0.06,0.18"; }
public readonly struct Assets_Revolver { public const string Id = "revolver"; public const string Bundle = "models"; public const string Key = "0dbb5142230adc84292865064219a5d3"; public const string MeshName = "Revolver_Body"; public const string TextureKey = "647dea7a4421fff41bbcd2f00080eb39"; public const float Height = 0.7f; public const float RotateX = 0.0f; public const float RotateY = 0.0f; public const float RotateZ = 0.0f; public const string IdleClip = "Idle"; public const string FireClip = "Shoot"; public const string WalkClip = "none"; public const string ArmColor = "0.02,0.06,0.18"; }
public readonly struct Assets_Shotgun { public const string Id = "shotgun"; public const string Bundle = "models"; public const string Key = "e1e497dbbcf47df49a1b3d23fd1b4994"; public const string MeshName = "Shotgun_New"; public const string TextureKey = "20c9f6d019cb72f49b178539f13f5377"; public const float Height = 0.75f; public const float RotateX = 90.0f; public const float RotateY = 0.0f; public const float RotateZ = 0.0f; public const string IdleClip = "Idle"; public const string FireClip = "FireNoReload"; public const string WalkClip = "none"; public const string ArmColor = "0.02,0.06,0.18"; }
public readonly struct Assets_Coin { public const string Id = "coin"; public const string Bundle = "models"; public const string Key = "fb46724754ff9044b80f6df9d583440d"; public const string MeshName = "Cylinder"; public const string TextureKey = "none"; public const float Height = 0.12f; public const float RotateX = 0.0f; public const float RotateY = 0.0f; public const float RotateZ = 0.0f; public const string IdleClip = "none"; public const string FireClip = "none"; public const string WalkClip = "none"; public const string ArmColor = "none"; }
public readonly struct Audio_Revolver { public const string Id = "revolver"; public const string Key = "631df62232be137469c054e1d18be525"; public const string Name = "AltRevolverShoot1"; public const float Volume = 0.45f; }
public readonly struct Audio_Shotgun { public const string Id = "shotgun"; public const string Key = "f23557a9aad66fe49a1a5fe56d222698"; public const string Name = "Steampunk Weapons - Shotgun 2 - Shot - 01"; public const float Volume = 0.6f; }
public readonly struct Audio_Coin { public const string Id = "coin"; public const string Key = "ce77e27cc9789704dbeb0a0525e4d23b"; public const string Name = "coinflip"; public const float Volume = 0.3f; }
public readonly struct Controls_Dash { public const string Id = "dash"; public const string Mode = "game"; public const string Path = "Sprint"; public const string Action = "dash"; }
public readonly struct Controls_Slide { public const string Id = "slide"; public const string Mode = "game"; public const string Path = "Crouch"; public const string Action = "slide"; }
public readonly struct Controls_Fire { public const string Id = "fire"; public const string Mode = "custom"; public const string Path = "<Mouse>/leftButton"; public const string Action = "fire"; }
public readonly struct Controls_Coin { public const string Id = "coin"; public const string Mode = "custom"; public const string Path = "<Mouse>/rightButton"; public const string Action = "coin"; }
public readonly struct Controls_Parry { public const string Id = "parry"; public const string Mode = "custom"; public const string Path = "<Keyboard>/f"; public const string Action = "parry"; }
public readonly struct Controls_Equip { public const string Id = "equip"; public const string Mode = "custom"; public const string Path = "<Keyboard>/g"; public const string Action = "equip"; }
public readonly struct Controls_Switch { public const string Id = "switch"; public const string Mode = "custom"; public const string Path = "<Keyboard>/r"; public const string Action = "switch"; }
public readonly struct Hooks_Movement { public const string Id = "movement"; public const string Type = "PlayerController"; public const string Member = "FixedUpdate"; public const string Phase = "postfix: native slide velocity"; public const string System = "movement"; public const string Source = "PlayerController.cs"; }
public readonly struct Hooks_Parry { public const string Id = "parry"; public const string Type = "PlayerHealth"; public const string Member = "Hurt"; public const string Phase = "prefix"; public const string System = "parry"; public const string Source = "PlayerHealth.cs"; }
public readonly struct Hooks_Damage { public const string Id = "damage"; public const string Type = "EnemyHealth"; public const string Member = "Hurt"; public const string Phase = "host call"; public const string System = "weapons"; public const string Source = "EnemyHealth.cs"; }
public readonly struct Hooks_Input { public const string Id = "input"; public const string Type = "InputManager"; public const string Member = "GetAction"; public const string Phase = "read saved bindings"; public const string System = "controls"; public const string Source = "InputManager.cs"; }
public readonly struct Hooks_Avatars { public const string Id = "avatars"; public const string Type = "SemiFunc"; public const string Member = "PlayerGetList"; public const string Phase = "read on main thread"; public const string System = "assets"; public const string Source = "SemiFunc.cs"; }
public readonly struct Hooks_Session { public const string Id = "session"; public const string Type = "SteamManager"; public const string Member = "Start"; public const string Phase = "native join arg"; public const string System = "network"; public const string Source = "SteamManager.cs"; }
public readonly struct Hooks_GrabHold { public const string Id = "grab-hold"; public const string Type = "InputManager"; public const string Member = "KeyHold"; public const string Phase = "prefix while gun drawn"; public const string System = "controls"; public const string Source = "InputManager.cs"; }
public readonly struct Hooks_GrabDown { public const string Id = "grab-down"; public const string Type = "InputManager"; public const string Member = "KeyDown"; public const string Phase = "prefix while gun drawn"; public const string System = "controls"; public const string Source = "InputManager.cs"; }
public readonly struct Hooks_EnemyCollider { public const string Id = "enemy-collider"; public const string Type = "EnemyParent"; public const string Member = "Awake"; public const string Phase = "resolve physics collider to child EnemyHealth"; public const string System = "weapons"; public const string Source = "EnemyParent.cs"; }
public readonly struct Hooks_SlamFall { public const string Id = "slam-fall"; public const string Type = "PlayerCollisionController"; public const string Member = "ResetFalling"; public const string Phase = "call during intentional slam"; public const string System = "movement"; public const string Source = "PlayerCollisionController.cs"; }
public readonly struct Hooks_TestTumble { public const string Id = "test-tumble"; public const string Type = "PlayerTumble"; public const string Member = "TumbleSet"; public const string Phase = "development-only positioning"; public const string System = "presentation"; public const string Source = "PlayerTumble.cs"; }
public readonly struct Hooks_EnemyIndex { public const string Id = "enemy-index"; public const string Type = "SemiFunc"; public const string Member = "EnemyGetFromIndex"; public const string Phase = "native attacker index for parry"; public const string System = "parry"; public const string Source = "SemiFunc.cs"; }
public readonly struct Lifecycle_Bootstrap { public const string Id = "bootstrap"; public const bool HideManager = true; public const string GameplayScenes = "level,tutorial,lobby"; public const string ResetPolicy = "death and controller replacement"; public const string MixedLobbyPolicy = "disable mod gameplay and restore native movement/body until all peers have matching ready assets"; public const string ReadyGate = "controller native LateStart has populated original movement values; required local meshes, rigs, idle/fire/run clips, weapon textures and three sounds are ready on every matching peer"; public const string AssetEnv = "ULTRAHAUL_ULTRAKILL"; public const string NetworkStart = "Wait for native multiplayer state before reading Photon or attaching its event listener; native region lookup initializes it first."; public const string RestoreMovement = "Restore native walk, sprint, crouch, jump, gravity, slide duration and slide decay when mod gameplay is disabled."; }
public readonly struct Loot_Fragile { public const string Id = "fragile"; public const string DamagePolicy = "native"; public const string ValuePolicy = "native"; public const string GrabPolicy = "native when holstered"; public const float BulletImpulse = 1.5f; public const float BlastImpulse = 2.0f; }
public readonly struct Movement_V1 { public const string Id = "v1"; public const float Walk = 7.0f; public const float Sprint = 10.0f; public const float Crouch = 3.0f; public const float Jump = 10.0f; public const float Gravity = 20.0f; public const float DashSpeed = 23.0f; public const float DashSeconds = 0.16f; public const float DashCapacity = 3.0f; public const float DashRecharge = 0.65f; public const float SlideSpeed = 16.0f; public const float SlideDecay = 0.5f; public const float SlamSpeed = 27.0f; public const float CarryMultiplier = 0.75f; public const float SlideSeconds = 2.0f; public const string SlideEntry = "press native crouch while moving on ground; sprint-to-slide also works"; public const string SlamFallPolicy = "Reset native fall distance during intentional slam descent and landing; retain native damage on ordinary falls and loot."; }
public readonly struct Network_Coop { public const string Id = "coop"; public const int EventCode = 181; public const int MaxPlayers = 6; public const string Protocol = "UH-1"; public const string Transport = "native Steam + Photon PUN relay"; public const string HandshakeKey = "UltraHaulProtocol"; public const float ShotTolerance = 6.0f; public const float RateLimit = 0.1f; public const string JoinArg = "+connect_lobby"; public const string EndEvents = "host broadcasts consumed coins and shell impacts to all peers"; public const string ParryTarget = "native EnemyDirector index, identical to incoming PlayerHealth.Hurt attacker index"; }
public readonly struct Parry_Feedback { public const string Id = "feedback"; public const float Window = 0.22f; public const float Cooldown = 0.55f; public const float Range = 3.0f; public const int Damage = 35; public const float StunSeconds = 0.6f; public const int CoinCapacity = 4; public const float CoinRecharge = 3.0f; public const float CoinLife = 2.0f; public const float CoinUp = 6.0f; public const float CoinForward = 3.0f; public const float CoinMultiplier = 2.0f; public const float CoinHitRadius = 0.22f; }
public readonly struct Presentation_Hud { public const string Id = "hud"; public const string Title = "ULTRA R.E.P.O."; public const int HudWidth = 420; public const int HudHeight = 190; public const float ScanSeconds = 2.0f; public const float TracerSeconds = 0.12f; public const float ViewX = 0.22f; public const float ViewY = -0.24f; public const float ViewZ = 0.55f; public const float Recoil = 0.08f; public const string TestBridge = "{localappdata}/UltraHaul/dev"; public const float HudX = 24.0f; public const float HudY = 220.0f; public const int FontSize = 26; public const float ReferenceHeight = 1080.0f; public const string TestSlotEnv = "ULTRAHAUL_DEV_SLOT"; public const float TestHeadroom = 3.0f; public const float TestDropHeight = 2.0f; public const string TestEnemy = "Huntsman"; public const string ShotTrace = "Development-only ray command logs actual camera aim, native target and every ray collider; never active in normal play."; public const string TestPosition = "Native TumbleSet ends test ragdoll before teleport; synchronize controller transform/rigidbody and reset native fall accumulator and prior height. Isolated combat uses the native Huntsman at close range. Boost check fires and parries in the same frame before this close target intercepts the shell."; }
public readonly struct Style_Momentum { public const string Id = "momentum"; public const float MaxScore = 600.0f; public const float Decay = 40.0f; public const float Grace = 3.0f; public const float Hit = 12.0f; public const float Kill = 85.0f; public const float Coin = 55.0f; public const float Parry = 100.0f; public const float Boost = 75.0f; public const float VarietyMultiplier = 1.25f; public const float StaleMultiplier = 0.35f; public const float EnergyPerPoint = 0.007f; public const float BoostThreshold = 160.0f; public const float BoostSeconds = 3.0f; public const float CombatMultiplier = 1.2f; }
public readonly struct Weapons_Revolver { public const string Id = "revolver"; public const string Asset = "revolver"; public const int Damage = 24; public const int Pellets = 1; public const float Cooldown = 0.38f; public const float Range = 80.0f; public const float Spread = 0.0f; public const float Speed = 0.0f; public const float Lifetime = 0.0f; public const float BoostWindow = 0.0f; public const int BoostDamage = 0; public const float BlastRadius = 0.0f; public const string FireTiming = "Previous accepted shot determines next allowed time, including when switching weapons; client and host share this rule."; }
public readonly struct Weapons_Shotgun { public const string Id = "shotgun"; public const string Asset = "shotgun"; public const int Damage = 8; public const int Pellets = 8; public const float Cooldown = 0.95f; public const float Range = 40.0f; public const float Spread = 4.0f; public const float Speed = 42.0f; public const float Lifetime = 1.2f; public const float BoostWindow = 0.22f; public const int BoostDamage = 60; public const float BlastRadius = 2.5f; public const string FireTiming = "Previous accepted shot determines next allowed time, including when switching weapons; client and host share this rule."; }
}
